- kind: environment
  name: dev
  data:
    type: parquet
    path: s3a://cortex-examples/reviews.parquet
    schema:
      - column_name: review
        feature_name: review
      - column_name: label
        feature_name: label
